name: convert_widget_image_example

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  path_provider:
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.3.0
  permission_handler_platform_interface: ^3.7.0
  flutter_svg: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - assets/images/